### ISSUE TITLE
Check-in 9f6a18e Breaks Ability to Build Code

### ISSUE THREAD

**Issue by patricksalo** [mikecotrone/PhoneFormattingTextfield#1]
Hi Mike,

You probably haven't noticed, but it looks like the merge you did with check-in 9f6a18e breaks the ability to build the project. The problem is that the following two files:

Demo_Window.xojo_window
phoneNumberFormatTextfield.xojo_code

Get littered with...

"<<<<<<< HEAD"
">>>>>>> master"
"======="

...which causes Xojo to not be happy when loading up the project. The current workaround I'm using is to grab the prior check-in, 3ef3c1c.

Patrick

**Comment by mikecotrone** [comment]
Thanks Patrick. I'll get it fixed up here this weekend.

**Comment by mikecotrone** [comment]
Fixed - Thanks!
